import string
import random
import math

class Botplayer:

    def __init__(self, G):
        # identity

        name = ''.join(random.choices(string.ascii_letters + string.digits, k=5))
        name = "Player_" + name
        while name in G.player_names:
            name = "Player_" + ''.join(
                random.choices(string.ascii_letters + string.digits, k=5)
            )
        self.name = name
        G.player_names.append(name)

        self.gs = G

        # status
        self.alive = True
        self.aliveBefore = True

        self.connected = True # Keep track if the player is connected
        self.hijacked = False

        # skill
        self.skill = None
        # ownership
        self.territories = []
        self.capital = None   # Name of the capital
        # battle stats
        self.temp_stats = None   # determine after deployment stage to prevent infinite growth
        self.industrial = 6
        self.infrastructure = 3
        self.infrastructure_upgrade = 0
        self.min_roll = 1
        # hidden resources
        self.stars = 0
        self.reserves = 0
        self.s_city_amt = 0  # city amount to settle in innerAsync actions
        self.m_city_amt = 0  # megacity amount to settle in innerAsync actions
        # alliance
        self.hasAllies = False
        self.allies = []
        self.ally_socket = None
        # turn
        self.conquered = False
        self.game = G
        # visuals
        self.color = None
        self.insignia = None
        # puppet state
        self.puppet = False
        self.master = None
        self.vassals = []
        # deployment
        self.deployable_amt = 0
        # economy
        self.cumulative_gdp = 0
        # summit
        self.num_summit = 2
        self.num_global_cease = 1
        # status monitoringg
        self.total_troops = 0
        # Player Power Index
        self.PPI = 0
        # number of leylines controlled by player
        self.numLeylines = 0

        self.con_amt = 0    # keep counts of how many territories the player has conquered during a turn

        # keep track of how many exploration made
        self.land_explored = []
        self.sunken_cost = 0

        # 
        self.isBot = True

        self.skill_options = None

        self.continent_tendency = {}

        # Perceivable Stats Coeffient -> Disparity between On field upgrade and structures of enemy and you converted into a multiplier

        # Worth Point -> How much does a territory worth

        # Stability memory -> the longer a continent is built up and occupied, the more attachment

        # Continental Worth Coefficient -> How much troop is generated. How many Worth Points the Continent has. How important was the Continent.
        # How many enemy faced. How many chokepoints.

        # Territorial Expansion Decision Chain:

        # Internal
        # Given a set of territories, what's the:
        # Easiest Obtainable continent:
            # How many troops to enemy ratio (PSC adjusted)
        # How much troops is generated by a continent
        # Easiness x Gain = Total Worth Point of a continent
        # Summary: How Easy x How much Gain

    def get_worthy_continent_from_set(self, curr_dist, setupmode=False):
        obtainable_continents = []

        for cont_name, cont_data in self.gs.map.conts.items():
            cont_territories = set(cont_data['trtys'])
            # A continent is obtainable if any territory in curr_dist belongs to it
            if cont_territories.intersection(curr_dist):
                obtainable_continents.append(cont_name)

        if not obtainable_continents:
            return None

        best_continent = None
        best_score = -1

        for cont_name in obtainable_continents:
            score = self.get_continental_worth_points(cont_name, curr_dist, setupmode)

            if score > best_score:
                best_score = score
                best_continent = cont_name

        return best_continent, best_score

    # Function Used to determine the worthiness of a unconquered territory
    def get_continental_worth_points(self, cont_name, curr_dist, setupmode):
        # Easiness
        NumF = 0
        NumN = 0
        for trty in self.gs.map.conts[cont_name]['trtys']:
            if trty in curr_dist:
                mul = 1 if self.gs.map.territories[trty].isCapital else 0
                mulc = 1 if self.gs.map.territories[trty].isCity else 0
                NumF += self.gs.map.territories[trty].troops + (mul * 5) + (mulc * 3)
            else:
                mul = 1 if self.gs.map.territories[trty].isCapital else 0
                mulc = 1 if self.gs.map.territories[trty].isCity else 0
                NumN += self.gs.map.territories[trty].troops + (mul * 5) + (mulc * 3)
        if NumN == 0:
            if setupmode:
                return math.log(1+NumF)**2 * self.gs.map.conts[cont_name]['bonus']
            else:
                return -100
        easiness = math.log(1 + NumF/NumN)

        # Bonus
        bonus = self.gs.map.conts[cont_name]['bonus']

        score = ( easiness * bonus )
        return score

    def choose_territory(self,):
        """
        Choose a good territorial distribution
        """
        
        curr_choice =  None
        curr_best_score = -100
        for choice in self.gs.aval_choices:
            curr_dist = self.gs.aval_choices[choice]
            _ , curr_score = self.get_worthy_continent_from_set(curr_dist, True)
            if curr_score > curr_best_score:
                curr_choice = choice
                curr_best_score = curr_score
        
        self.gs.server.sleep(15)

        self.territories = self.gs.aval_choices[curr_choice]
        del self.gs.aval_choices[curr_choice]
        self.color = curr_choice

        for trty in self.territories:
            self.gs.server.emit('update_trty_display', {trty: {'color': self.color, 'troops': 1}}, room=self.gs.lobby)
        self.gs.GES.selected += 1

    # Set Capital
    def set_capital(self, ):
        location = self.get_best_defendable_territory(self.territories)
        self.capital = self.gs.map.territories[location].name
        self.gs.map.territories[location].isCapital = True
        self.gs.server.emit('update_trty_display', {location: {'isCapital': True, 'capital_color': self.color}}, room=self.gs.lobby)
        self.gs.GES.selected += 1
        return
    
    # Set cities
    def set_cities(self, N):
        locations = self.get_best_territories_to_build(self.territories, N, "cities")
        for location in locations:
            self.gs.map.territories[location].isCity = True
            self.gs.server.emit('update_trty_display', {location: {'hasDev': 'city'}}, room=self.gs.lobby)
        self.gs.GES.selected += 1
        self.gs.server.emit('cityBuildingSFX', room=self.gs.lobby)
        return
    
    # Initial Deployment
    def deploy_troops(self):
        locations = self.get_best_territories_to_defend(self.territories)
        total_deployable = self.deployable_amt

        capital_tid = locations["capital"]
        city_tids = locations["cities"]

        # --- Split deployable amount ---
        has_capital = capital_tid is not None
        has_cities = len(city_tids) > 0

        if has_capital and has_cities:
            capital_share = total_deployable // (1+len(city_tids))
            cities_share = total_deployable - capital_share
        elif has_capital and not has_cities:
            capital_share = total_deployable
            cities_share = 0
        elif has_cities and not has_capital:
            capital_share = 0
            cities_share = total_deployable
        else:
            return  # nothing to deploy to

        # --- Deploy to capital ---
        if has_capital:
            self.gs.map.territories[capital_tid].troops += capital_share

            self.gs.server.emit('selectionSoundFx', room=self.gs.lobby)

            self.gs.server.emit('troop_addition_display', {f'{capital_tid}': {'tid': capital_tid, 'number': capital_share},}, room=self.gs.lobby)
            self.gs.server.emit('update_trty_display',{capital_tid:{'troops':self.gs.map.territories[capital_tid].troops}}, room=self.gs.lobby)

        # --- Deploy equally to cities ---
        if has_cities:
            per_city = cities_share // len(city_tids)
            city_leftover = cities_share - (per_city * len(city_tids))

            for tid in city_tids:
                self.gs.map.territories[tid].troops += per_city

                self.gs.server.emit('troop_addition_display', { f'{tid}': {'tid': tid, 'number': per_city},}, room=self.gs.lobby)
                self.gs.server.emit('update_trty_display',{tid:{'troops':self.gs.map.territories[tid].troops}}, room=self.gs.lobby)

            # City leftover also goes to capital, or first city if no capital
            if city_leftover > 0:
                if has_capital:
                    self.gs.map.territories[capital_tid].troops += city_leftover

                    self.gs.server.emit('troop_addition_display', { f'{tid}': {'tid': tid, 'number': per_city},}, room=self.gs.lobby)
                    self.gs.server.emit('update_trty_display',{tid:{'troops':self.gs.map.territories[tid].troops}}, room=self.gs.lobby)
                else:
                    self.gs.map.territories[city_tids[0]].troops += city_leftover

                    self.gs.server.emit('troop_addition_display', { f'{tid}': {'tid': tid, 'number': per_city},}, room=self.gs.lobby)
                    self.gs.server.emit('update_trty_display',{tid:{'troops':self.gs.map.territories[tid].troops}}, room=self.gs.lobby)

            self.gs.server.emit('selectionSoundFx', room=self.gs.lobby)
        
        self.deployable_amt = 0

        if self.gs.GES.current_event == None:
            self.gs.GES.selected += 1

    def choose_skill(self):
        option = random.choice(self.skill_options)
        for pid in self.gs.players:
            if self.gs.players[pid].name == self.name:
                self.skill = self.gs.SDIS.initiate_skill(option, pid, self.gs)
                break
        self.gs.GES.selected += 1

    def get_best_defendable_territory(self, tid_list):
        """
        Given a list of TIDs, find the best defendable territory within
        the worthy continent based on fewest enemies and chokepoints within radius 2.
        """
        # Step 1: Find the worthy continent
        worthy_cont, _ = self.get_worthy_continent_from_set(tid_list, True)
        if worthy_cont is None:
            return None

        cont_tids = set(self.gs.map.conts[worthy_cont]['trtys'])

        # Step 2: Filter tid_list to only those in the worthy continent
        candidates = [tid for tid in tid_list if tid in cont_tids]
        if not candidates:
            return None

        # Step 3: Score each candidate
        best_tid = None
        best_score = float('inf')  # lower is better

        for tid in candidates:
            nearby = self.get_neighbors_within_radius(tid, 2)

            # Count enemies: TIDs in radius-2 that are NOT in our tid_list
            tid_set = set(tid_list)
            enemy_count = sum(1 for n in nearby if n not in tid_set)

            # Count chokepoints: territories in radius-2 that are chokepoints
            chokepoint_count = sum(1 for n in nearby if self.is_chokepoint(n))

            # Lower score = more defendable
            score = enemy_count + (chokepoint_count)**(2.5)

            if score < best_score:
                best_score = score
                best_tid = tid

        return best_tid
    
    def get_neighbors_within_radius(self, start_tid, radius):
        visited = {start_tid}
        frontier = {start_tid}
        for _ in range(radius):
            next_frontier = set()
            for tid in frontier:
                for neighbor in self.gs.map.territories[tid].neighbors:
                    if neighbor not in visited:
                        visited.add(neighbor)
                        next_frontier.add(neighbor)
            frontier = next_frontier
        visited.discard(start_tid)
        return visited

    def is_chokepoint(self, tid):
        territory_cont = None
        for cont_name, cont_data in self.gs.map.conts.items():
            if tid in cont_data['trtys']:
                territory_cont = set(cont_data['trtys'])
                break
        if territory_cont is None:
            return False
        return any(n not in territory_cont for n in self.gs.map.territories[tid].neighbors)
    

    def get_best_territories_to_build(self, tid_list, N, build_type):
        """
        Returns top N territories to build upon, ranked by strategic score.
        """
        # Step 1: Filter valid territories
        valid = []
        if build_type == "cities":
            valid = [tid for tid in tid_list if not self.gs.map.territories[tid].isCity] if build_type == "cities" else list(tid_list)
        if not valid:
            return []

        tid_set = set(tid_list)

        # --- Determine Priority Tiers ---

        # Tier 1: Continents the player already fully controls
        controlled_conts = set()
        for cont_name, cont_data in self.gs.map.conts.items():
            if all(t in tid_set for t in cont_data['trtys']):
                controlled_conts.add(cont_name)

        # Tier 2: Most worthy potential continent (existing logic)
        worthy_cont, _ = self.get_worthy_continent_from_set(tid_list, True)

        # Map each TID to its continent
        def get_continent(tid):
            for cont_name, cont_data in self.gs.map.conts.items():
                if tid in cont_data['trtys']:
                    return cont_name
            return None

        # --- Score each valid territory ---
        scored = []

        for tid in valid:
            territory = self.gs.map.territories[tid]
            cont_name = get_continent(tid)

            # -- Proximity modifier for chokepoints (weighted by distance) --
            radius1 = self.get_neighbors_within_radius(tid, 1)
            radius2 = self.get_neighbors_within_radius(tid, 2)
            ring2_only = radius2 - radius1  # neighbors exactly 2 steps away

            chokepoint_penalty = 0
            for n in radius1:
                if self.is_chokepoint(n):
                    chokepoint_penalty += 2.0   # closer chokepoints hurt more
            for n in ring2_only:
                if self.is_chokepoint(n):
                    chokepoint_penalty += 1.0   # further chokepoints hurt less

            # -- Friendly troops on this territory (higher = better) --
            friendly_troops = territory.troops

            # -- Enemy troops in surrounding 2 layers (higher = worse) --
            enemy_troops = 0
            for n in radius2:
                if n not in tid_set:
                    enemy_troops += self.gs.map.territories[n].troops

            # Raw defendability score
            raw_score = ((friendly_troops * 2) / (max(enemy_troops, 1) * 1.5)) * 100

            # -- Apply tier multiplier --
            if cont_name in controlled_conts:
                multiplier = 2.0    # Tier 1: already control this continent
            elif cont_name == worthy_cont:
                multiplier = 1.5    # Tier 2: most worthy potential continent
            else:
                multiplier = 1.0    # Tier 3: everything else

            final_score = raw_score * multiplier - (chokepoint_penalty ** 2)
            scored.append((tid, final_score))

        # Sort descending by score, return top N TIDs
        scored.sort(key=lambda x: x[1], reverse=True)
        return [tid for tid, _ in scored[:N]]
    
    def get_best_territories_to_defend(self, tid_list):
        tid_set = set(tid_list)

        # -------------------------
        # 1. Controlled continents
        # -------------------------
        controlled_conts = {}
        cont_troop_totals = {}

        for cont_name, cont_data in self.gs.map.conts.items():
            cont_tids = cont_data['trtys']
            if all(t in tid_set for t in cont_tids):
                # Find chokepoints within this continent
                chokepoints = [t for t in cont_tids if self.is_chokepoint(t)]
                controlled_conts[cont_name] = chokepoints
                cont_troop_totals[cont_name] = sum(
                    self.gs.map.territories[t].troops for t in cont_tids
                )

        # Sort controlled_conts by total troops descending
        controlled_conts = dict(
            sorted(controlled_conts.items(),
                key=lambda x: cont_troop_totals[x[0]],
                reverse=True)
        )

        # -------------------------
        # 2. Capital(s)
        # -------------------------
        my_capital_tid = None
        other_capitals = []

        for tid in tid_list:
            territory = self.gs.map.territories[tid]
            if territory.isCapital:
                if territory.name == self.capital:
                    my_capital_tid = tid
                else:
                    other_capitals.append(tid)

        # -------------------------
        # 3. Cities
        # -------------------------
        cities = [tid for tid in tid_list if self.gs.map.territories[tid].isCity]

        # -------------------------
        # 4. Other special categories
        # -------------------------
        megacities       = [tid for tid in tid_list if self.gs.map.territories[tid].isMegacity]
        transport_centers = [tid for tid in tid_list if self.gs.map.territories[tid].isTransportcenter]
        forts            = [tid for tid in tid_list if self.gs.map.territories[tid].isFort]
        halls            = [tid for tid in tid_list if self.gs.map.territories[tid].isHall]
        leylines         = [tid for tid in tid_list if self.gs.map.territories[tid].isLeyline]
        bureaus          = [tid for tid in tid_list if self.gs.map.territories[tid].isBureau]

        # -------------------------
        # 5. High value TIDs scoring
        # -------------------------
        scored = []
        for tid in tid_list:
            t = self.gs.map.territories[tid]
            points = 0

            if t.isMegacity:        points += 50
            if t.isTransportcenter: points += 40
            if t.isHall:            points += 50
            if t.isLeyline:         points += 15
            if t.isBureau:          points += 15
            if self.is_chokepoint(tid): points += 15

            if points > 0:
                scored.append((tid, points))

        scored.sort(key=lambda x: x[1], reverse=True)
        high_value_tids = [tid for tid, _ in scored]

        # -------------------------
        # 6. Build and return result
        # -------------------------
        return {
            "controlled_conts":   controlled_conts,
            "capital":            my_capital_tid,
            "capitals":           other_capitals,
            "cities":             cities,
            "megacities":         megacities,
            "transport_centers":  transport_centers,
            "forts":              forts,
            "halls":              halls,
            "leylines":           leylines,
            "bureaus":            bureaus,
            "high_value_tids":    high_value_tids,
        }